
server:
  port: 8088
  servlet:
    context-path: /thanhdat

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/thanh_dat
    username: postgres
    password: 123456
  config:
    import: optional:application-dev.yml
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  flyway:
    enabled: false
    driver-class-name: org.postgresql.Driver

