
server:
  port: 8088
  servlet:
    context-path: /thanhdat

spring:
  config:
    import: optional:application-dev.yml
  security:
    user:
      name: admin
      password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  flyway:
    enabled: false
    driver-class-name: org.postgresql.Driver